'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace Microsoft.WindowsAPICodePack.ShellExtensions.Resources


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")> _
	<System.Diagnostics.DebuggerNonUserCodeAttribute> _
	<System.Runtime.CompilerServices.CompilerGeneratedAttribute> _
	Friend Class LocalizedMessages

		Private Shared resourceMan As Global.System.Resources.ResourceManager

		Private Shared resourceCulture As Global.System.Globalization.CultureInfo

		<System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
		Friend Sub New()
		End Sub

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Microsoft.WindowsAPICodePack.ShellExtensions.Resources.LocalizedMessages", GetType(LocalizedMessages).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set
				resourceCulture = value
			End Set
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Control has not yet been assigned. Methods requiring it cannot be called..
		''' </summary>
		Friend Shared ReadOnly Property PreviewHandlerControlNotInitialized() As String
			Get
				Return ResourceManager.GetString("PreviewHandlerControlNotInitialized", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to {0} must implement one or more of IPreviewFromStream, IPreviewFromShellObject or IPreviewFromFile..
		''' </summary>
		Friend Shared ReadOnly Property PreviewHandlerInterfaceNotImplemented() As String
			Get
				Return ResourceManager.GetString("PreviewHandlerInterfaceNotImplemented", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to PreviewHandler &apos;{0}&apos; must have exactly one PreviewHandler attribute..
		''' </summary>
		Friend Shared ReadOnly Property PreviewHandlerInvalidAttributes() As String
			Get
				Return ResourceManager.GetString("PreviewHandlerInvalidAttributes", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Unable to call interface {0} because it is not supported on this object..
		''' </summary>
		Friend Shared ReadOnly Property PreviewHandlerUnsupportedInterfaceCalled() As String
			Get
				Return ResourceManager.GetString("PreviewHandlerUnsupportedInterfaceCalled", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to The sum of offset and count must be less than or equal to the size of the buffer..
		''' </summary>
		Friend Shared ReadOnly Property StorageStreamBufferOverflow() As String
			Get
				Return ResourceManager.GetString("StorageStreamBufferOverflow", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Count must be greater than or equal to zero..
		''' </summary>
		Friend Shared ReadOnly Property StorageStreamCountLessThanZero() As String
			Get
				Return ResourceManager.GetString("StorageStreamCountLessThanZero", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to The stream was initialized as read-only..
		''' </summary>
		Friend Shared ReadOnly Property StorageStreamIsReadonly() As String
			Get
				Return ResourceManager.GetString("StorageStreamIsReadonly", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Offset must be greater than or equal to zero..
		''' </summary>
		Friend Shared ReadOnly Property StorageStreamOffsetLessThanZero() As String
			Get
				Return ResourceManager.GetString("StorageStreamOffsetLessThanZero", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to {0} does not implement IThumbnailFromStream and so requires DisableProcessIsolation set to true..
		''' </summary>
		Friend Shared ReadOnly Property ThumbnailProviderDisabledProcessIsolation() As String
			Get
				Return ResourceManager.GetString("ThumbnailProviderDisabledProcessIsolation", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to {0} must implement one or more of IThumbnailFromStream, IThumbnailFromShellObject or IThumbnailFromFile..
		''' </summary>
		Friend Shared ReadOnly Property ThumbnailProviderInterfaceNotImplemented() As String
			Get
				Return ResourceManager.GetString("ThumbnailProviderInterfaceNotImplemented", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Cannot retrieve handle because proxy window has not been created..
		''' </summary>
		Friend Shared ReadOnly Property WpfPreviewHandlerNoHandle() As String
			Get
				Return ResourceManager.GetString("WpfPreviewHandlerNoHandle", resourceCulture)
			End Get
		End Property
	End Class
End Namespace
