-- MySQL Script generated by MySQL Workbench
-- Tue Jun  2 18:18:03 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema license_keys
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `license_keys` ;

-- -----------------------------------------------------
-- Schema license_keys
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `license_keys` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `license_keys` ;

-- -----------------------------------------------------
-- Table `license`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `license` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `license` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `hashcode` VARCHAR(1024) NOT NULL,
  `expired_time` DATE NOT NULL,
  `add_time` DATE NOT NULL DEFAULT now(),
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `license` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `user_info_idx` ON `license` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `passwd` VARCHAR(2048) NOT NULL,
  `institution` MEDIUMTEXT NULL,
  `licenses` INT UNSIGNED NOT NULL DEFAULT 0,
  `add_time` DATE NOT NULL DEFAULT now(),
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `user` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unique_user` ON `user` (`email` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
