'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports RibbonLib
Imports RibbonLib.Controls

Namespace RibbonLib.Controls
    Partial Class RibbonItems
        Private Class Cmd
            Public Const cmdMenuMain As UInteger = 5
            Public Const cmdGroupExcelPad As UInteger = 4
            Public Const cmdButtonOpen As UInteger = 2
            Public Const cmdButtonImportsData As UInteger = 3
        End Class

        ' ContextPopup CommandName

        Private _ribbon As Ribbon
        Public ReadOnly Property Ribbon As Ribbon
            Get
                Return _ribbon
            End Get
        End Property
        Private _MenuMain As RibbonTab
        Public ReadOnly Property MenuMain As RibbonTab
            Get
                Return _MenuMain
            End Get
        End Property
        Private _GroupExcelPad As RibbonGroup
        Public ReadOnly Property GroupExcelPad As RibbonGroup
            Get
                Return _GroupExcelPad
            End Get
        End Property
        Private _ButtonOpen As RibbonButton
        Public ReadOnly Property ButtonOpen As RibbonButton
            Get
                Return _ButtonOpen
            End Get
        End Property
        Private _ButtonImportsData As RibbonButton
        Public ReadOnly Property ButtonImportsData As RibbonButton
            Get
                Return _ButtonImportsData
            End Get
        End Property

        Public Sub New(ByVal ribbon As Ribbon)
            If ribbon Is Nothing Then
                Throw New ArgumentNullException(NameOf(ribbon), "Parameter is Nothing")
            End If
            _ribbon = ribbon
            _MenuMain = New RibbonTab(_ribbon, Cmd.cmdMenuMain)
            _GroupExcelPad = New RibbonGroup(_ribbon, Cmd.cmdGroupExcelPad)
            _ButtonOpen = New RibbonButton(_ribbon, Cmd.cmdButtonOpen)
            _ButtonImportsData = New RibbonButton(_ribbon, Cmd.cmdButtonImportsData)
        End Sub

    End Class
End Namespace
