//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using RibbonLib;
using RibbonLib.Controls;

namespace RibbonLib.Controls
{
    partial class RibbonItems
    {
        private static class Cmd
        {
            public const uint cmdMenuMain = 5;
            public const uint cmdGroupExcelPad = 4;
            public const uint cmdButtonOpen = 2;
            public const uint cmdButtonImportsData = 3;
        }

        // ContextPopup CommandName

        public Ribbon Ribbon { get; private set; }
        public RibbonTab MenuMain { get; private set; }
        public RibbonGroup GroupExcelPad { get; private set; }
        public RibbonButton ButtonOpen { get; private set; }
        public RibbonButton ButtonImportsData { get; private set; }

        public RibbonItems(Ribbon ribbon)
        {
            if (ribbon == null)
                throw new ArgumentNullException(nameof(ribbon), "Parameter is null");
            this.Ribbon = ribbon;
            MenuMain = new RibbonTab(ribbon, Cmd.cmdMenuMain);
            GroupExcelPad = new RibbonGroup(ribbon, Cmd.cmdGroupExcelPad);
            ButtonOpen = new RibbonButton(ribbon, Cmd.cmdButtonOpen);
            ButtonImportsData = new RibbonButton(ribbon, Cmd.cmdButtonImportsData);
        }

    }
}
