'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports RibbonLib
Imports RibbonLib.Controls

Namespace RibbonLib.Controls
    Partial Class RibbonItems
        Private Class Cmd
            Public Const cmdButtonOpen As UInteger = 2
        End Class

        ' ContextPopup CommandName

        Private _ribbon As Ribbon
        Public ReadOnly Property Ribbon As Ribbon
            Get
                Return _ribbon
            End Get
        End Property
        Private _ButtonOpen As RibbonButton
        Public ReadOnly Property ButtonOpen As RibbonButton
            Get
                Return _ButtonOpen
            End Get
        End Property

        Public Sub New(ByVal ribbon As Ribbon)
            If ribbon Is Nothing Then
                Throw New ArgumentNullException(NameOf(ribbon), "Parameter is Nothing")
            End If
            _ribbon = ribbon
            _ButtonOpen = New RibbonButton(_ribbon, Cmd.cmdButtonOpen)
        End Sub

    End Class
End Namespace
