'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Docking.
        '''</summary>
        Friend ReadOnly Property Category_Docking() As String
            Get
                Return ResourceManager.GetString("Category_Docking", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Docking Notification.
        '''</summary>
        Friend ReadOnly Property Category_DockingNotification() As String
            Get
                Return ResourceManager.GetString("Category_DockingNotification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Property Changed.
        '''</summary>
        Friend ReadOnly Property Category_PropertyChanged() As String
            Get
                Return ResourceManager.GetString("Category_PropertyChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Float).
        '''</summary>
        Friend ReadOnly Property DockAreaEditor_FloatCheckBoxText() As String
            Get
                Return ResourceManager.GetString("DockAreaEditor_FloatCheckBoxText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Determines if end user drag and drop docking is allowed..
        '''</summary>
        Friend ReadOnly Property DockContent_AllowEndUserDocking_Description() As String
            Get
                Return ResourceManager.GetString("DockContent_AllowEndUserDocking_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The size to display the content in auto hide mode. Value &lt; 1 to specify the size in portion; value &gt;= 1 to specify the size in pixel..
        '''</summary>
        Friend ReadOnly Property DockContent_AutoHidePortion_Description() As String
            Get
                Return ResourceManager.GetString("DockContent_AutoHidePortion_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enable/Disable the close button of the content..
        '''</summary>
        Friend ReadOnly Property DockContent_CloseButton_Description() As String
            Get
                Return ResourceManager.GetString("DockContent_CloseButton_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The form must be of type IDockContent..
        '''</summary>
        Friend ReadOnly Property DockContent_Constructor_InvalidForm() As String
            Get
                Return ResourceManager.GetString("DockContent_Constructor_InvalidForm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gets or sets a value indicating in which area of the DockPanel the content allowed to show..
        '''</summary>
        Friend ReadOnly Property DockContent_DockAreas_Description() As String
            Get
                Return ResourceManager.GetString("DockContent_DockAreas_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Occurs when the value of DockState property changed..
        '''</summary>
        Friend ReadOnly Property DockContent_DockStateChanged_Description() As String
            Get
                Return ResourceManager.GetString("DockContent_DockStateChanged_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indicates the content will be hidden instead of being closed..
        '''</summary>
        Friend ReadOnly Property DockContent_HideOnClose_Description() As String
            Get
                Return ResourceManager.GetString("DockContent_HideOnClose_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The desired docking state when first showing..
        '''</summary>
        Friend ReadOnly Property DockContent_ShowHint_Description() As String
            Get
                Return ResourceManager.GetString("DockContent_ShowHint_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Context menu displayed for the dock pane tab strip..
        '''</summary>
        Friend ReadOnly Property DockContent_TabPageContextMenu_Description() As String
            Get
                Return ResourceManager.GetString("DockContent_TabPageContextMenu_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The tab text displayed in the dock pane. If not set, the Text property will be used..
        '''</summary>
        Friend ReadOnly Property DockContent_TabText_Description() As String
            Get
                Return ResourceManager.GetString("DockContent_TabText_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The text displayed when mouse hovers over the tab..
        '''</summary>
        Friend ReadOnly Property DockContent_ToolTipText_Description() As String
            Get
                Return ResourceManager.GetString("DockContent_ToolTipText_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The provided value is out of range..
        '''</summary>
        Friend ReadOnly Property DockContentHandler_AutoHidePortion_OutOfRange() As String
            Get
                Return ResourceManager.GetString("DockContentHandler_AutoHidePortion_OutOfRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Value: The value of DockAreas conflicts with current DockState..
        '''</summary>
        Friend ReadOnly Property DockContentHandler_DockAreas_InvalidValue() As String
            Get
                Return ResourceManager.GetString("DockContentHandler_DockAreas_InvalidValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The pane is invalid. Check the IsFloat and DockPanel properties of this dock pane..
        '''</summary>
        Friend ReadOnly Property DockContentHandler_DockPane_InvalidValue() As String
            Get
                Return ResourceManager.GetString("DockContentHandler_DockPane_InvalidValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The pane is invalid. Check the IsFloat and DockPanel properties of this dock pane..
        '''</summary>
        Friend ReadOnly Property DockContentHandler_FloatPane_InvalidValue() As String
            Get
                Return ResourceManager.GetString("DockContentHandler_FloatPane_InvalidValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid value, conflicts with DockableAreas  property..
        '''</summary>
        Friend ReadOnly Property DockContentHandler_IsFloat_InvalidValue() As String
            Get
                Return ResourceManager.GetString("DockContentHandler_IsFloat_InvalidValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The dock state is invalid..
        '''</summary>
        Friend ReadOnly Property DockContentHandler_SetDockState_InvalidState() As String
            Get
                Return ResourceManager.GetString("DockContentHandler_SetDockState_InvalidState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The dock panel is null..
        '''</summary>
        Friend ReadOnly Property DockContentHandler_SetDockState_NullPanel() As String
            Get
                Return ResourceManager.GetString("DockContentHandler_SetDockState_NullPanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid beforeContent, it must be contained by the pane..
        '''</summary>
        Friend ReadOnly Property DockContentHandler_Show_InvalidBeforeContent() As String
            Get
                Return ResourceManager.GetString("DockContentHandler_Show_InvalidBeforeContent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid DockState: Content can not be showed as &quot;Unknown&quot; or &quot;Hidden&quot;..
        '''</summary>
        Friend ReadOnly Property DockContentHandler_Show_InvalidDockState() As String
            Get
                Return ResourceManager.GetString("DockContentHandler_Show_InvalidDockState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The previous pane is invalid. It can not be null, and its docking state must not be auto-hide..
        '''</summary>
        Friend ReadOnly Property DockContentHandler_Show_InvalidPrevPane() As String
            Get
                Return ResourceManager.GetString("DockContentHandler_Show_InvalidPrevPane", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DockPanel can not be null..
        '''</summary>
        Friend ReadOnly Property DockContentHandler_Show_NullDockPanel() As String
            Get
                Return ResourceManager.GetString("DockContentHandler_Show_NullDockPanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Pane can not be null..
        '''</summary>
        Friend ReadOnly Property DockContentHandler_Show_NullPane() As String
            Get
                Return ResourceManager.GetString("DockContentHandler_Show_NullPane", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid value, check DockableAreas property..
        '''</summary>
        Friend ReadOnly Property DockContentHandler_ShowHint_InvalidValue() As String
            Get
                Return ResourceManager.GetString("DockContentHandler_ShowHint_InvalidValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Context menu displayed for the dock pane tab strip..
        '''</summary>
        Friend ReadOnly Property DockHandler_TabPageContextMenuStrip_Description() As String
            Get
                Return ResourceManager.GetString("DockHandler_TabPageContextMenuStrip_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dockindicator_PaneDiamond_Hotspot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dockindicator_PaneDiamond_Hotspot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DockIndicator_PaneDiamond_HotspotIndex() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DockIndicator_PaneDiamond_HotspotIndex", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Press SHIFT for docking to full side..
        '''</summary>
        Friend ReadOnly Property DockIndicator_ToolTipText() As String
            Get
                Return ResourceManager.GetString("DockIndicator_ToolTipText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Content: ActiveContent must be one of the visible contents, or null if there is no visible content..
        '''</summary>
        Friend ReadOnly Property DockPane_ActiveContent_InvalidValue() As String
            Get
                Return ResourceManager.GetString("DockPane_ActiveContent_InvalidValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid argument: Content can not be &quot;null&quot;..
        '''</summary>
        Friend ReadOnly Property DockPane_Constructor_NullContent() As String
            Get
                Return ResourceManager.GetString("DockPane_Constructor_NullContent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid argument: The content&apos;s DockPanel can not be &quot;null&quot;..
        '''</summary>
        Friend ReadOnly Property DockPane_Constructor_NullDockPanel() As String
            Get
                Return ResourceManager.GetString("DockPane_Constructor_NullDockPanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The specified container conflicts with the IsFloat property..
        '''</summary>
        Friend ReadOnly Property DockPane_DockTo_InvalidContainer() As String
            Get
                Return ResourceManager.GetString("DockPane_DockTo_InvalidContainer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The previous pane does not exist in the nested docking pane collection..
        '''</summary>
        Friend ReadOnly Property DockPane_DockTo_NoPrevPane() As String
            Get
                Return ResourceManager.GetString("DockPane_DockTo_NoPrevPane", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The container can not be null..
        '''</summary>
        Friend ReadOnly Property DockPane_DockTo_NullContainer() As String
            Get
                Return ResourceManager.GetString("DockPane_DockTo_NullContainer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The previous pane can not be null when the nested docking pane collection is not empty..
        '''</summary>
        Friend ReadOnly Property DockPane_DockTo_NullPrevPane() As String
            Get
                Return ResourceManager.GetString("DockPane_DockTo_NullPrevPane", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The previous pane can not be itself..
        '''</summary>
        Friend ReadOnly Property DockPane_DockTo_SelfPrevPane() As String
            Get
                Return ResourceManager.GetString("DockPane_DockTo_SelfPrevPane", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FloatWindow property can not be set to &quot;null&quot; when DockState is DockState.Float..
        '''</summary>
        Friend ReadOnly Property DockPane_FloatWindow_InvalidValue() As String
            Get
                Return ResourceManager.GetString("DockPane_FloatWindow_InvalidValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Content: Content not within the collection..
        '''</summary>
        Friend ReadOnly Property DockPane_SetContentIndex_InvalidContent() As String
            Get
                Return ResourceManager.GetString("DockPane_SetContentIndex_InvalidContent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Index: The index is out of range..
        '''</summary>
        Friend ReadOnly Property DockPane_SetContentIndex_InvalidIndex() As String
            Get
                Return ResourceManager.GetString("DockPane_SetContentIndex_InvalidIndex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The state for the dock pane is invalid..
        '''</summary>
        Friend ReadOnly Property DockPane_SetDockState_InvalidState() As String
            Get
                Return ResourceManager.GetString("DockPane_SetDockState_InvalidState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auto Hide.
        '''</summary>
        Friend ReadOnly Property DockPaneCaption_ToolTipAutoHide() As String
            Get
                Return ResourceManager.GetString("DockPaneCaption_ToolTipAutoHide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Friend ReadOnly Property DockPaneCaption_ToolTipClose() As String
            Get
                Return ResourceManager.GetString("DockPaneCaption_ToolTipClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Window Position.
        '''</summary>
        Friend ReadOnly Property DockPaneCaption_ToolTipOptions() As String
            Get
                Return ResourceManager.GetString("DockPaneCaption_ToolTipOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Window List.
        '''</summary>
        Friend ReadOnly Property DockPaneStrip_ToolTipWindowList() As String
            Get
                Return ResourceManager.GetString("DockPaneStrip_ToolTipWindowList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskArrowBottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskArrowBottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskArrowLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskArrowLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskArrowRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskArrowRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskArrowTop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskArrowTop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskCoreBottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskCoreBottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskCoreCenter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskCoreCenter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskCoreLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskCoreLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskCoreRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskCoreRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskCoreTop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskCoreTop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskDock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskDock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskDockFive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskDockFive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskTabClose() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskTabClose", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskTabList() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskTabList", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskTabOverflow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskTabOverflow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskToolWindowAutoHide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskToolWindowAutoHide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskToolWindowClose() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskToolWindowClose", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskToolWindowDock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskToolWindowDock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskToolWindowOption() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskToolWindowOption", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskWindowBottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskWindowBottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskWindowCenter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskWindowCenter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskWindowLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskWindowLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskWindowRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskWindowRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaskWindowTop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskWindowTop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to vsTheme2015.
        '''</summary>
        Friend ReadOnly Property ThemeVersion() As String
            Get
                Return ResourceManager.GetString("ThemeVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property vs2015blue_vstheme() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("vs2015blue_vstheme", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property vs2015dark_vstheme() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("vs2015dark_vstheme", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property vs2015light_vstheme() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("vs2015light_vstheme", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
