'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace Microsoft.WindowsAPICodePack.Shell.Resources


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")> _
	<System.Diagnostics.DebuggerNonUserCodeAttribute> _
	<System.Runtime.CompilerServices.CompilerGeneratedAttribute> _
	Friend Class LocalizedMessages

		Private Shared resourceMan As Global.System.Resources.ResourceManager

		Private Shared resourceCulture As Global.System.Globalization.CultureInfo

		<System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
		Friend Sub New()
		End Sub

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Microsoft.WindowsAPICodePack.Shell.Resources.LocalizedMessages", GetType(LocalizedMessages).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set
				resourceCulture = value
			End Set
		End Property

		''' <summary>
		'''   Looks up a localized string similar to AddToMostRecentlyUsedList cannot be changed while dialog is showing..
		''' </summary>
		Friend Shared ReadOnly Property AddToMostRecentlyUsedListCannotBeChanged() As String
			Get
				Return ResourceManager.GetString("AddToMostRecentlyUsedListCannotBeChanged", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to AlwaysAppendDefaultExtension cannot be changed while dialog is showing..
		''' </summary>
		Friend Shared ReadOnly Property AlwaysAppendDefaultExtensionCannotBeChanged() As String
			Get
				Return ResourceManager.GetString("AlwaysAppendDefaultExtensionCannotBeChanged", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Index was outside the bounds of the CommonFileDialogComboBox..
		''' </summary>
		Friend Shared ReadOnly Property ComboBoxIndexOutsideBounds() As String
			Get
				Return ResourceManager.GetString("ComboBoxIndexOutsideBounds", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to File name not available - dialog was canceled..
		''' </summary>
		Friend Shared ReadOnly Property CommonFileDialogCanceled() As String
			Get
				Return ResourceManager.GetString("CommonFileDialogCanceled", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Shell item could not be created..
		''' </summary>
		Friend Shared ReadOnly Property CommonFileDialogCannotCreateShellItem() As String
			Get
				Return ResourceManager.GetString("CommonFileDialogCannotCreateShellItem", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Handle provided cannot be IntPtr.Zero..
		''' </summary>
		Friend Shared ReadOnly Property CommonFileDialogInvalidHandle() As String
			Get
				Return ResourceManager.GetString("CommonFileDialogInvalidHandle", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Multiple files selected - the FileNames property should be used instead..
		''' </summary>
		Friend Shared ReadOnly Property CommonFileDialogMultipleFiles() As String
			Get
				Return ResourceManager.GetString("CommonFileDialogMultipleFiles", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Multiple files selected - the Items property should be used instead..
		''' </summary>
		Friend Shared ReadOnly Property CommonFileDialogMultipleItems() As String
			Get
				Return ResourceManager.GetString("CommonFileDialogMultipleItems", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to File name not available - dialog has not closed yet..
		''' </summary>
		Friend Shared ReadOnly Property CommonFileDialogNotClosed() As String
			Get
				Return ResourceManager.GetString("CommonFileDialogNotClosed", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Common File Dialog requires Windows Vista or later..
		''' </summary>
		Friend Shared ReadOnly Property CommonFileDialogRequiresVista() As String
			Get
				Return ResourceManager.GetString("CommonFileDialogRequiresVista", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Office Files.
		''' </summary>
		Friend Shared ReadOnly Property CommonFiltersOffice() As String
			Get
				Return ResourceManager.GetString("CommonFiltersOffice", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to All Picture Files.
		''' </summary>
		Friend Shared ReadOnly Property CommonFiltersPicture() As String
			Get
				Return ResourceManager.GetString("CommonFiltersPicture", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Text Files.
		''' </summary>
		Friend Shared ReadOnly Property CommonFiltersText() As String
			Get
				Return ResourceManager.GetString("CommonFiltersText", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to CreatePrompt cannot be changed while dialog is showing..
		''' </summary>
		Friend Shared ReadOnly Property CreatePromptCannotBeChanged() As String
			Get
				Return ResourceManager.GetString("CreatePromptCannotBeChanged", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Custom controls cannot be removed from a File dialog once added..
		''' </summary>
		Friend Shared ReadOnly Property DialogControlCollectionCannotRemoveControls() As String
			Get
				Return ResourceManager.GetString("DialogControlCollectionCannotRemoveControls", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Control name cannot be null or zero length..
		''' </summary>
		Friend Shared ReadOnly Property DialogControlCollectionEmptyName() As String
			Get
				Return ResourceManager.GetString("DialogControlCollectionEmptyName", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to CommonFileDialogMenuItem controls can only be added to CommonFileDialogMenu controls..
		''' </summary>
		Friend Shared ReadOnly Property DialogControlCollectionMenuItemControlsCannotBeAdded() As String
			Get
				Return ResourceManager.GetString("DialogControlCollectionMenuItemControlsCannotBeAdded", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Modifying controls collection while dialog is showing is not supported..
		''' </summary>
		Friend Shared ReadOnly Property DialogControlCollectionModifyingControls() As String
			Get
				Return ResourceManager.GetString("DialogControlCollectionModifyingControls", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Dialog cannot have more than one control with the same name..
		''' </summary>
		Friend Shared ReadOnly Property DialogControlCollectionMoreThanOneControl() As String
			Get
				Return ResourceManager.GetString("DialogControlCollectionMoreThanOneControl", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Dialog control must be removed from current collections first..
		''' </summary>
		Friend Shared ReadOnly Property DialogControlCollectionRemoveControlFirst() As String
			Get
				Return ResourceManager.GetString("DialogControlCollectionRemoveControlFirst", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to EnsureFileExists cannot be changed while dialog is showing..
		''' </summary>
		Friend Shared ReadOnly Property EnsureFileExistsCannotBeChanged() As String
			Get
				Return ResourceManager.GetString("EnsureFileExistsCannotBeChanged", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to EnsurePathExists cannot be changed while dialog is showing..
		''' </summary>
		Friend Shared ReadOnly Property EnsurePathExistsCannotBeChanged() As String
			Get
				Return ResourceManager.GetString("EnsurePathExistsCannotBeChanged", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to EnsureReadOnly cannot be changed while dialog is showing..
		''' </summary>
		Friend Shared ReadOnly Property EnsureReadonlyCannotBeChanged() As String
			Get
				Return ResourceManager.GetString("EnsureReadonlyCannotBeChanged", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to EnsureValidNames cannot be changed while dialog is showing..
		''' </summary>
		Friend Shared ReadOnly Property EnsureValidNamesCannotBeChanged() As String
			Get
				Return ResourceManager.GetString("EnsureValidNamesCannotBeChanged", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Browsing to object failed..
		''' </summary>
		Friend Shared ReadOnly Property ExplorerBrowserBrowseToObjectFailed() As String
			Get
				Return ResourceManager.GetString("ExplorerBrowserBrowseToObjectFailed", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to ExplorerBrowser failed to get current view..
		''' </summary>
		Friend Shared ReadOnly Property ExplorerBrowserFailedToGetView() As String
			Get
				Return ResourceManager.GetString("ExplorerBrowserFailedToGetView", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Unable to get icon size..
		''' </summary>
		Friend Shared ReadOnly Property ExplorerBrowserIconSize() As String
			Get
				Return ResourceManager.GetString("ExplorerBrowserIconSize", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Unexpected error retrieving item count..
		''' </summary>
		Friend Shared ReadOnly Property ExplorerBrowserItemCount() As String
			Get
				Return ResourceManager.GetString("ExplorerBrowserItemCount", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Unexpected error retrieving selected item count..
		''' </summary>
		Friend Shared ReadOnly Property ExplorerBrowserSelectedItemCount() As String
			Get
				Return ResourceManager.GetString("ExplorerBrowserSelectedItemCount", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Unexpected error retrieving selection..
		''' </summary>
		Friend Shared ReadOnly Property ExplorerBrowserUnexpectedError() As String
			Get
				Return ResourceManager.GetString("ExplorerBrowserUnexpectedError", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Unexpected error retrieving view items..
		''' </summary>
		Friend Shared ReadOnly Property ExplorerBrowserViewItems() As String
			Get
				Return ResourceManager.GetString("ExplorerBrowserViewItems", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to The given path does not exist ({0}).
		''' </summary>
		Friend Shared ReadOnly Property FilePathNotExist() As String
			Get
				Return ResourceManager.GetString("FilePathNotExist", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Guid does not identify a known folder..
		''' </summary>
		Friend Shared ReadOnly Property FolderIdsUnknownGuid() As String
			Get
				Return ResourceManager.GetString("FolderIdsUnknownGuid", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to ControlPanel Category.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeCategory() As String
			Get
				Return ResourceManager.GetString("FolderTypeCategory", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to ControlPanel Classic.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeClassic() As String
			Get
				Return ResourceManager.GetString("FolderTypeClassic", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Communications.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeCommunications() As String
			Get
				Return ResourceManager.GetString("FolderTypeCommunications", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Compressed Folder.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeCompressedFolder() As String
			Get
				Return ResourceManager.GetString("FolderTypeCompressedFolder", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Contacts.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeContacts() As String
			Get
				Return ResourceManager.GetString("FolderTypeContacts", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Documents.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeDocuments() As String
			Get
				Return ResourceManager.GetString("FolderTypeDocuments", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Games.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeGames() As String
			Get
				Return ResourceManager.GetString("FolderTypeGames", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Generic Library.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeGenericLibrary() As String
			Get
				Return ResourceManager.GetString("FolderTypeGenericLibrary", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Invalid.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeInvalid() As String
			Get
				Return ResourceManager.GetString("FolderTypeInvalid", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Library.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeLibrary() As String
			Get
				Return ResourceManager.GetString("FolderTypeLibrary", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Music.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeMusic() As String
			Get
				Return ResourceManager.GetString("FolderTypeMusic", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Music Icons.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeMusicIcons() As String
			Get
				Return ResourceManager.GetString("FolderTypeMusicIcons", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Network Explorer.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeNetworkExplorer() As String
			Get
				Return ResourceManager.GetString("FolderTypeNetworkExplorer", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Not Specified.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeNotSpecified() As String
			Get
				Return ResourceManager.GetString("FolderTypeNotSpecified", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Open Search.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeOpenSearch() As String
			Get
				Return ResourceManager.GetString("FolderTypeOpenSearch", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Other Users.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeOtherUsers() As String
			Get
				Return ResourceManager.GetString("FolderTypeOtherUsers", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Pictures.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypePictures() As String
			Get
				Return ResourceManager.GetString("FolderTypePictures", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Printers.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypePrinters() As String
			Get
				Return ResourceManager.GetString("FolderTypePrinters", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to RecordedTV.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeRecordedTV() As String
			Get
				Return ResourceManager.GetString("FolderTypeRecordedTV", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to RecycleBin.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeRecycleBin() As String
			Get
				Return ResourceManager.GetString("FolderTypeRecycleBin", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Saved Games.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeSavedGames() As String
			Get
				Return ResourceManager.GetString("FolderTypeSavedGames", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Search Connector.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeSearchConnector() As String
			Get
				Return ResourceManager.GetString("FolderTypeSearchConnector", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Searches.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeSearches() As String
			Get
				Return ResourceManager.GetString("FolderTypeSearches", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Generic SearchResults.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeSearchResults() As String
			Get
				Return ResourceManager.GetString("FolderTypeSearchResults", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Software Explorer.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeSoftwareExplorer() As String
			Get
				Return ResourceManager.GetString("FolderTypeSoftwareExplorer", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to User Files.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeUserFiles() As String
			Get
				Return ResourceManager.GetString("FolderTypeUserFiles", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Users Libraries.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeUserLibraries() As String
			Get
				Return ResourceManager.GetString("FolderTypeUserLibraries", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Videos.
		''' </summary>
		Friend Shared ReadOnly Property FolderTypeVideos() As String
			Get
				Return ResourceManager.GetString("FolderTypeVideos", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to IsExpandedMode cannot be changed while dialog is showing..
		''' </summary>
		Friend Shared ReadOnly Property IsExpandedModeCannotBeChanged() As String
			Get
				Return ResourceManager.GetString("IsExpandedModeCannotBeChanged", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Custom categories cannot be added while recent documents tracking is turned off..
		''' </summary>
		Friend Shared ReadOnly Property JumpListCustomCategoriesDisabled() As String
			Get
				Return ResourceManager.GetString("JumpListCustomCategoriesDisabled", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to The file type is not registered with this application..
		''' </summary>
		Friend Shared ReadOnly Property JumpListFileTypeNotRegistered() As String
			Get
				Return ResourceManager.GetString("JumpListFileTypeNotRegistered", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to JumpListLink&apos;s path is required and cannot be null..
		''' </summary>
		Friend Shared ReadOnly Property JumpListLinkPathRequired() As String
			Get
				Return ResourceManager.GetString("JumpListLinkPathRequired", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to JumpListLink&apos;s title is required and cannot be null..
		''' </summary>
		Friend Shared ReadOnly Property JumpListLinkTitleRequired() As String
			Get
				Return ResourceManager.GetString("JumpListLinkTitleRequired", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Negative numbers are not allowed for the ordinal position..
		''' </summary>
		Friend Shared ReadOnly Property JumpListNegativeOrdinalPosition() As String
			Get
				Return ResourceManager.GetString("JumpListNegativeOrdinalPosition", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Given Known Folder ID is invalid..
		''' </summary>
		Friend Shared ReadOnly Property KnownFolderInvalidGuid() As String
			Get
				Return ResourceManager.GetString("KnownFolderInvalidGuid", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Parsing name is invalid..
		''' </summary>
		Friend Shared ReadOnly Property KnownFolderParsingName() As String
			Get
				Return ResourceManager.GetString("KnownFolderParsingName", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Creation of window has failed, view inner exception for details..
		''' </summary>
		Friend Shared ReadOnly Property MessageListenerCannotCreateWindow() As String
			Get
				Return ResourceManager.GetString("MessageListenerCannotCreateWindow", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Window class could not be registered, check inner exception for more details..
		''' </summary>
		Friend Shared ReadOnly Property MessageListenerClassNotRegistered() As String
			Get
				Return ResourceManager.GetString("MessageListenerClassNotRegistered", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Message filter registration failed..
		''' </summary>
		Friend Shared ReadOnly Property MessageListenerFilterUnableToRegister() As String
			Get
				Return ResourceManager.GetString("MessageListenerFilterUnableToRegister", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to No listener handled of that value is registered..
		''' </summary>
		Friend Shared ReadOnly Property MessageListenerFilterUnknownListenerHandle() As String
			Get
				Return ResourceManager.GetString("MessageListenerFilterUnknownListenerHandle", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Cannot create window on the listener thread because there is no existing window on the listener thread..
		''' </summary>
		Friend Shared ReadOnly Property MessageListenerNoWindowHandle() As String
			Get
				Return ResourceManager.GetString("MessageListenerNoWindowHandle", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to NavigateToShortcut cannot be changed while dialog is showing..
		''' </summary>
		Friend Shared ReadOnly Property NavigateToShortcutCannotBeChanged() As String
			Get
				Return ResourceManager.GetString("NavigateToShortcutCannotBeChanged", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Parent cannot be null..
		''' </summary>
		Friend Shared ReadOnly Property NavigationLogNullParent() As String
			Get
				Return ResourceManager.GetString("NavigationLogNullParent", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to The method or operation is not implemented..
		''' </summary>
		Friend Shared ReadOnly Property NotImplementedException() As String
			Get
				Return ResourceManager.GetString("NotImplementedException", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to OverwritePrompt cannot be changed while dialog is showing..
		''' </summary>
		Friend Shared ReadOnly Property OverwritePromptCannotBeChanged() As String
			Get
				Return ResourceManager.GetString("OverwritePromptCannotBeChanged", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to This CanonicalName is not a valid index..
		''' </summary>
		Friend Shared ReadOnly Property PropertyCollectionCanonicalInvalidIndex() As String
			Get
				Return ResourceManager.GetString("PropertyCollectionCanonicalInvalidIndex", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to This PropertyKey is not a valid index..
		''' </summary>
		Friend Shared ReadOnly Property PropertyCollectionInvalidIndex() As String
			Get
				Return ResourceManager.GetString("PropertyCollectionInvalidIndex", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Argument CanonicalName cannot be null or empty..
		''' </summary>
		Friend Shared ReadOnly Property PropertyCollectionNullCanonicalName() As String
			Get
				Return ResourceManager.GetString("PropertyCollectionNullCanonicalName", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Index was outside the bounds of the CommonFileDialogRadioButtonList..
		''' </summary>
		Friend Shared ReadOnly Property RadioButtonListIndexOutOfBounds() As String
			Get
				Return ResourceManager.GetString("RadioButtonListIndexOutOfBounds", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to RestoreDirectory cannot be changed while dialog is showing..
		''' </summary>
		Friend Shared ReadOnly Property RestoreDirectoryCannotBeChanged() As String
			Get
				Return ResourceManager.GetString("RestoreDirectoryCannotBeChanged", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Retrieved a null shell item from dialog..
		''' </summary>
		Friend Shared ReadOnly Property SaveFileNullItem() As String
			Get
				Return ResourceManager.GetString("SaveFileNullItem", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Given property key is invalid..
		''' </summary>
		Friend Shared ReadOnly Property SearchConditionFactoryInvalidProperty() As String
			Get
				Return ResourceManager.GetString("SearchConditionFactoryInvalidProperty", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Shell Exception has occurred, look at inner exception for information..
		''' </summary>
		Friend Shared ReadOnly Property ShellExceptionDefaultText() As String
			Get
				Return ResourceManager.GetString("ShellExceptionDefaultText", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to GetParsingName has failed..
		''' </summary>
		Friend Shared ReadOnly Property ShellHelperGetParsingNameFailed() As String
			Get
				Return ResourceManager.GetString("ShellHelperGetParsingNameFailed", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to The given CanonicalName is not valid..
		''' </summary>
		Friend Shared ReadOnly Property ShellInvalidCanonicalName() As String
			Get
				Return ResourceManager.GetString("ShellInvalidCanonicalName", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to DefaultSaveFolder path not found..
		''' </summary>
		Friend Shared ReadOnly Property ShellLibraryDefaultSaveFolderNotFound() As String
			Get
				Return ResourceManager.GetString("ShellLibraryDefaultSaveFolderNotFound", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to LibraryName cannot be empty..
		''' </summary>
		Friend Shared ReadOnly Property ShellLibraryEmptyName() As String
			Get
				Return ResourceManager.GetString("ShellLibraryEmptyName", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Folder path not found..
		''' </summary>
		Friend Shared ReadOnly Property ShellLibraryFolderNotFound() As String
			Get
				Return ResourceManager.GetString("ShellLibraryFolderNotFound", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Invalid FolderType Guid..
		''' </summary>
		Friend Shared ReadOnly Property ShellLibraryInvalidFolderType() As String
			Get
				Return ResourceManager.GetString("ShellLibraryInvalidFolderType", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to The given known folder is not a valid library..
		''' </summary>
		Friend Shared ReadOnly Property ShellLibraryInvalidLibrary() As String
			Get
				Return ResourceManager.GetString("ShellLibraryInvalidLibrary", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Can&apos;t get the display name..
		''' </summary>
		Friend Shared ReadOnly Property ShellObjectCannotGetDisplayName() As String
			Get
				Return ResourceManager.GetString("ShellObjectCannotGetDisplayName", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Destination array too small, or invalid arrayIndex..
		''' </summary>
		Friend Shared ReadOnly Property ShellObjectCollectionArrayTooSmall() As String
			Get
				Return ResourceManager.GetString("ShellObjectCollectionArrayTooSmall", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Must have at least one shell object in the collection..
		''' </summary>
		Friend Shared ReadOnly Property ShellObjectCollectionEmptyCollection() As String
			Get
				Return ResourceManager.GetString("ShellObjectCollectionEmptyCollection", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Cannot insert items into a read only list..
		''' </summary>
		Friend Shared ReadOnly Property ShellObjectCollectionInsertReadOnly() As String
			Get
				Return ResourceManager.GetString("ShellObjectCollectionInsertReadOnly", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Cannot remove items from a read only list..
		''' </summary>
		Friend Shared ReadOnly Property ShellObjectCollectionRemoveReadOnly() As String
			Get
				Return ResourceManager.GetString("ShellObjectCollectionRemoveReadOnly", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Shell item could not be created..
		''' </summary>
		Friend Shared ReadOnly Property ShellObjectCreationFailed() As String
			Get
				Return ResourceManager.GetString("ShellObjectCreationFailed", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Shell Object creation requires Windows Vista or higher operating system..
		''' </summary>
		Friend Shared ReadOnly Property ShellObjectFactoryPlatformNotSupported() As String
			Get
				Return ResourceManager.GetString("ShellObjectFactoryPlatformNotSupported", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Unable to Create Shell Item..
		''' </summary>
		Friend Shared ReadOnly Property ShellObjectFactoryUnableToCreateItem() As String
			Get
				Return ResourceManager.GetString("ShellObjectFactoryUnableToCreateItem", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Registration for change notification has failed..
		''' </summary>
		Friend Shared ReadOnly Property ShellObjectWatcherRegisterFailed() As String
			Get
				Return ResourceManager.GetString("ShellObjectWatcherRegisterFailed", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Unable to change watched events while listening..
		''' </summary>
		Friend Shared ReadOnly Property ShellObjectWatcherUnableToChangeEvents() As String
			Get
				Return ResourceManager.GetString("ShellObjectWatcherUnableToChangeEvents", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to The value on this property cannot be set. To set the property value, use the ShellObject that is associated with this property..
		''' </summary>
		Friend Shared ReadOnly Property ShellPropertyCannotSetProperty() As String
			Get
				Return ResourceManager.GetString("ShellPropertyCannotSetProperty", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to No constructor found matching requested argument types..
		''' </summary>
		Friend Shared ReadOnly Property ShellPropertyFactoryConstructorNotFound() As String
			Get
				Return ResourceManager.GetString("ShellPropertyFactoryConstructorNotFound", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Unable to set property..
		''' </summary>
		Friend Shared ReadOnly Property ShellPropertySetValue() As String
			Get
				Return ResourceManager.GetString("ShellPropertySetValue", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Unable to get writable property store for this property..
		''' </summary>
		Friend Shared ReadOnly Property ShellPropertyUnableToGetWritableProperty() As String
			Get
				Return ResourceManager.GetString("ShellPropertyUnableToGetWritableProperty", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to A value had to be truncated in a string or rounded if a numeric value. Set AllowTruncatedValue to true to prevent this exception..
		''' </summary>
		Friend Shared ReadOnly Property ShellPropertyValueTruncated() As String
			Get
				Return ResourceManager.GetString("ShellPropertyValueTruncated", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to This Property is available on Windows 7 only..
		''' </summary>
		Friend Shared ReadOnly Property ShellPropertyWindows7() As String
			Get
				Return ResourceManager.GetString("ShellPropertyWindows7", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to This property only accepts a value of type \&quot;{0}\&quot;..
		''' </summary>
		Friend Shared ReadOnly Property ShellPropertyWrongType() As String
			Get
				Return ResourceManager.GetString("ShellPropertyWrongType", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Unable to set list of sort columns..
		''' </summary>
		Friend Shared ReadOnly Property ShellSearchFolderUnableToSetSortColumns() As String
			Get
				Return ResourceManager.GetString("ShellSearchFolderUnableToSetSortColumns", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Unable to set visible columns..
		''' </summary>
		Friend Shared ReadOnly Property ShellSearchFolderUnableToSetVisibleColumns() As String
			Get
				Return ResourceManager.GetString("ShellSearchFolderUnableToSetVisibleColumns", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to CurrentSize (width or height) cannot be greater than the maximum size: {0}..
		''' </summary>
		Friend Shared ReadOnly Property ShellThumbnailCurrentSizeRange() As String
			Get
				Return ResourceManager.GetString("ShellThumbnailCurrentSizeRange", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to The current ShellObject does not have a thumbnail. Try using ShellThumbnailFormatOption.Default to get the icon for this item..
		''' </summary>
		Friend Shared ReadOnly Property ShellThumbnailDoesNotHaveThumbnail() As String
			Get
				Return ResourceManager.GetString("ShellThumbnailDoesNotHaveThumbnail", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to The current ShellObject does not have a valid thumbnail handler or there was a problem in extracting the thumbnail for this specific shell object..
		''' </summary>
		Friend Shared ReadOnly Property ShellThumbnailNoHandler() As String
			Get
				Return ResourceManager.GetString("ShellThumbnailNoHandler", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to CurrentSize (width or height) cannot be 0..
		''' </summary>
		Friend Shared ReadOnly Property ShellThumbnailSizeCannotBe0() As String
			Get
				Return ResourceManager.GetString("ShellThumbnailSizeCannotBe0", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to ShowHiddenItems cannot be changed while dialog is showing..
		''' </summary>
		Friend Shared ReadOnly Property ShowHiddenItemsCannotBeChanged() As String
			Get
				Return ResourceManager.GetString("ShowHiddenItemsCannotBeChanged", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Show places list cannot be changed while dialog is showing..
		''' </summary>
		Friend Shared ReadOnly Property ShowPlacesListCannotBeChanged() As String
			Get
				Return ResourceManager.GetString("ShowPlacesListCannotBeChanged", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to The Stock Icon identifier given is invalid ({0})..
		''' </summary>
		Friend Shared ReadOnly Property StockIconInvalidGuid() As String
			Get
				Return ResourceManager.GetString("StockIconInvalidGuid", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Child control&apos;s window handle cannot be zero..
		''' </summary>
		Friend Shared ReadOnly Property TabbedThumbnailZeroChildHandle() As String
			Get
				Return ResourceManager.GetString("TabbedThumbnailZeroChildHandle", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Parent window handle cannot be zero..
		''' </summary>
		Friend Shared ReadOnly Property TabbedThumbnailZeroParentHandle() As String
			Get
				Return ResourceManager.GetString("TabbedThumbnailZeroParentHandle", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to TabbedThumbnailProxyWindow has not been set..
		''' </summary>
		Friend Shared ReadOnly Property TasbarWindowProxyWindowSet() As String
			Get
				Return ResourceManager.GetString("TasbarWindowProxyWindowSet", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to A valid active Window is needed to update the Taskbar..
		''' </summary>
		Friend Shared ReadOnly Property TaskbarManagerValidWindowRequired() As String
			Get
				Return ResourceManager.GetString("TaskbarManagerValidWindowRequired", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to The array of buttons must contain at least 1 item..
		''' </summary>
		Friend Shared ReadOnly Property TaskbarWindowEmptyButtonArray() As String
			Get
				Return ResourceManager.GetString("TaskbarWindowEmptyButtonArray", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Tool bar buttons for this window are already added. Please refer to the Remarks section of the AddButtons method for more information on updating the properties or hiding existing buttons..
		''' </summary>
		Friend Shared ReadOnly Property TaskbarWindowManagerButtonsAlreadyAdded() As String
			Get
				Return ResourceManager.GetString("TaskbarWindowManagerButtonsAlreadyAdded", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Value is already set. It cannot be set more than once..
		''' </summary>
		Friend Shared ReadOnly Property TaskbarWindowValueSet() As String
			Get
				Return ResourceManager.GetString("TaskbarWindowValueSet", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to The given control has not been added to the taskbar..
		''' </summary>
		Friend Shared ReadOnly Property ThumbnailManagerControlNotAdded() As String
			Get
				Return ResourceManager.GetString("ThumbnailManagerControlNotAdded", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Window handle is invalid..
		''' </summary>
		Friend Shared ReadOnly Property ThumbnailManagerInvalidHandle() As String
			Get
				Return ResourceManager.GetString("ThumbnailManagerInvalidHandle", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to This preview has already been added..
		''' </summary>
		Friend Shared ReadOnly Property ThumbnailManagerPreviewAdded() As String
			Get
				Return ResourceManager.GetString("ThumbnailManagerPreviewAdded", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to The given preview has not been added to the taskbar..
		''' </summary>
		Friend Shared ReadOnly Property ThumbnailManagerPreviewNotAdded() As String
			Get
				Return ResourceManager.GetString("ThumbnailManagerPreviewNotAdded", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Maximum number of buttons allowed is 7..
		''' </summary>
		Friend Shared ReadOnly Property ThumbnailToolbarManagerMaxButtons() As String
			Get
				Return ResourceManager.GetString("ThumbnailToolbarManagerMaxButtons", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Null or empty arrays are not allowed..
		''' </summary>
		Friend Shared ReadOnly Property ThumbnailToolbarManagerNullEmptyArray() As String
			Get
				Return ResourceManager.GetString("ThumbnailToolbarManagerNullEmptyArray", resourceCulture)
			End Get
		End Property
	End Class
End Namespace
