'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace Microsoft.WindowsAPICodePack.Sensors.Resources


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")> _
	<System.Diagnostics.DebuggerNonUserCodeAttribute> _
	<System.Runtime.CompilerServices.CompilerGeneratedAttribute> _
	Friend Class LocalizedMessages

		Private Shared resourceMan As Global.System.Resources.ResourceManager

		Private Shared resourceCulture As Global.System.Globalization.CultureInfo

		<System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
		Friend Sub New()
		End Sub

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Microsoft.WindowsAPICodePack.Sensors.Resources.LocalizedMessages", GetType(LocalizedMessages).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set
				resourceCulture = value
			End Set
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Data field array cannot be null or empty..
		''' </summary>
		Friend Shared ReadOnly Property SensorEmptyData() As String
			Get
				Return ResourceManager.GetString("SensorEmptyData", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Property keys array cannot be null or empty..
		''' </summary>
		Friend Shared ReadOnly Property SensorEmptyProperties() As String
			Get
				Return ResourceManager.GetString("SensorEmptyProperties", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Sensor id=&apos;{0}&apos; type=&apos;{1}&apos; category=&apos;{2}&apos; name=&apos;{3}&apos;..
		''' </summary>
		Friend Shared ReadOnly Property SensorGetString() As String
			Get
				Return ResourceManager.GetString("SensorGetString", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Sensors collection cannot be null or empty..
		''' </summary>
		Friend Shared ReadOnly Property SensorManagerEmptySensorsCollection() As String
			Get
				Return ResourceManager.GetString("SensorManagerEmptySensorsCollection", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Sensor not initialized..
		''' </summary>
		Friend Shared ReadOnly Property SensorNotInitialized() As String
			Get
				Return ResourceManager.GetString("SensorNotInitialized", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Data contains a null value at index {0}..
		''' </summary>
		Friend Shared ReadOnly Property SensorNullValueAtIndex() As String
			Get
				Return ResourceManager.GetString("SensorNullValueAtIndex", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Could not find property..
		''' </summary>
		Friend Shared ReadOnly Property SensorPropertyNotFound() As String
			Get
				Return ResourceManager.GetString("SensorPropertyNotFound", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to No sensors found. Are any sensor drivers installed?.
		''' </summary>
		Friend Shared ReadOnly Property SensorsNotFound() As String
			Get
				Return ResourceManager.GetString("SensorsNotFound", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Unable to get report from sensor..
		''' </summary>
		Friend Shared ReadOnly Property SensorUnableToGetReport() As String
			Get
				Return ResourceManager.GetString("SensorUnableToGetReport", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Unexpected pointer size..
		''' </summary>
		Friend Shared ReadOnly Property SensorUnexpectedPointerSize() As String
			Get
				Return ResourceManager.GetString("SensorUnexpectedPointerSize", resourceCulture)
			End Get
		End Property
	End Class
End Namespace
