'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace ThemeVS2012

    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    Friend Class vs2012IconResources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
            MyBase.New
        End Sub

        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("vs2012Resources", GetType(vs2012IconResources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = Value
            End Set
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Dockindicator_PaneDiamond_Hotspot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dockindicator_PaneDiamond_Hotspot", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property DockIndicator_PaneDiamond_HotspotIndex() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DockIndicator_PaneDiamond_HotspotIndex", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskArrowBottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskArrowBottom", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskArrowLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskArrowLeft", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskArrowRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskArrowRight", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskArrowTop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskArrowTop", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskCoreBottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskCoreBottom", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskCoreCenter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskCoreCenter", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskCoreLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskCoreLeft", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskCoreRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskCoreRight", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskCoreTop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskCoreTop", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskDock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskDock", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskDockFive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskDockFive", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskTabClose() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskTabClose", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskTabList() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskTabList", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskTabOverflow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskTabOverflow", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskToolWindowAutoHide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskToolWindowAutoHide", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskToolWindowClose() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskToolWindowClose", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskToolWindowDock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskToolWindowDock", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskToolWindowOption() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskToolWindowOption", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskWindowBottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskWindowBottom", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskWindowCenter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskWindowCenter", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskWindowLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskWindowLeft", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskWindowRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskWindowRight", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MaskWindowTop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaskWindowTop", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property vs2012blue_vstheme() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("vs2012blue_vstheme", resourceCulture)
                Return CType(obj, Byte())
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property vs2012dark_vstheme() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("vs2012dark_vstheme", resourceCulture)
                Return CType(obj, Byte())
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property vs2012light_vstheme() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("vs2012light_vstheme", resourceCulture)
                Return CType(obj, Byte())
            End Get
        End Property
    End Class
End Namespace
