//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using RibbonLib;
using RibbonLib.Controls;

namespace RibbonLib.Controls
{
    partial class RibbonItems
    {
        private static class Cmd
        {
            public const uint cmdButtonKeyGenerator = 2;
            public const uint cmdButtonLicenseGenerator = 3;
            public const uint cmdButtonLicenses = 6;
            public const uint cmdButtonExit = 7;
            public const uint cmdGroupMain = 5;
            public const uint cmdPanelMain = 4;
        }

        // ContextPopup CommandName

        public Ribbon Ribbon { get; private set; }
        public RibbonButton ButtonKeyGenerator { get; private set; }
        public RibbonButton ButtonLicenseGenerator { get; private set; }
        public RibbonButton ButtonLicenses { get; private set; }
        public RibbonButton ButtonExit { get; private set; }
        public RibbonTab GroupMain { get; private set; }
        public RibbonGroup PanelMain { get; private set; }

        public RibbonItems(Ribbon ribbon)
        {
            if (ribbon == null)
                throw new ArgumentNullException(nameof(ribbon), "Parameter is null");
            this.Ribbon = ribbon;
            ButtonKeyGenerator = new RibbonButton(ribbon, Cmd.cmdButtonKeyGenerator);
            ButtonLicenseGenerator = new RibbonButton(ribbon, Cmd.cmdButtonLicenseGenerator);
            ButtonLicenses = new RibbonButton(ribbon, Cmd.cmdButtonLicenses);
            ButtonExit = new RibbonButton(ribbon, Cmd.cmdButtonExit);
            GroupMain = new RibbonTab(ribbon, Cmd.cmdGroupMain);
            PanelMain = new RibbonGroup(ribbon, Cmd.cmdPanelMain);
        }

    }
}
