'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports RibbonLib
Imports RibbonLib.Controls

Namespace RibbonLib.Controls
    Partial Class RibbonItems
        Private Class Cmd
            Public Const cmdGroupMain As UInteger = 5
            Public Const cmdPanelMain As UInteger = 4
            Public Const cmdButtonKeyGenerator As UInteger = 2
            Public Const cmdButtonLicenseGenerator As UInteger = 3
        End Class

        ' ContextPopup CommandName

        Private _ribbon As Ribbon
        Public ReadOnly Property Ribbon As Ribbon
            Get
                Return _ribbon
            End Get
        End Property
        Private _GroupMain As RibbonTab
        Public ReadOnly Property GroupMain As RibbonTab
            Get
                Return _GroupMain
            End Get
        End Property
        Private _PanelMain As RibbonGroup
        Public ReadOnly Property PanelMain As RibbonGroup
            Get
                Return _PanelMain
            End Get
        End Property
        Private _ButtonKeyGenerator As RibbonButton
        Public ReadOnly Property ButtonKeyGenerator As RibbonButton
            Get
                Return _ButtonKeyGenerator
            End Get
        End Property
        Private _ButtonLicenseGenerator As RibbonButton
        Public ReadOnly Property ButtonLicenseGenerator As RibbonButton
            Get
                Return _ButtonLicenseGenerator
            End Get
        End Property

        Public Sub New(ByVal ribbon As Ribbon)
            If ribbon Is Nothing Then
                Throw New ArgumentNullException(NameOf(ribbon), "Parameter is Nothing")
            End If
            _ribbon = ribbon
            _GroupMain = New RibbonTab(_ribbon, Cmd.cmdGroupMain)
            _PanelMain = New RibbonGroup(_ribbon, Cmd.cmdPanelMain)
            _ButtonKeyGenerator = New RibbonButton(_ribbon, Cmd.cmdButtonKeyGenerator)
            _ButtonLicenseGenerator = New RibbonButton(_ribbon, Cmd.cmdButtonLicenseGenerator)
        End Sub

    End Class
End Namespace
